-- MySQL Script generated by MySQL Workbench
-- Wed Sep  6 11:35:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;
USE `mydb`;

-- Table Libros

DROP TABLE IF EXISTS `mydb`.`Libros`;

CREATE TABLE IF NOT EXISTS `mydb`.`Libros` (
  `idLibros` INT NULL,
  `name` VARCHAR(100) NULL,
  `summary` VARCHAR(1000) NULL,
  `category` VARCHAR(100) NULL,
  PRIMARY KEY (`idLibros`))
ENGINE = InnoDB;

-- Borrar registros
DELETE FROM Libros;

-- Reiniciar modos
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;